### ISSUE TITLE
Hexo博客SEO优化 | Ryuchen's 小栈

### ISSUE THREAD

**Issue by Ryuchen** [Ryuchen/Ryuchen.github.io#8]
https://ryuchen.github.io/2019/Hexo%E5%8D%9A%E5%AE%A2SEO%E4%BC%98%E5%8C%96/ 

 最近因为临近寒假课程也基本都结束了想着该把这个博客再好好维护一下了啊，所以想先把这个检索的功能优化加上，毕竟我是个爱显摆的人，写了没人看多令人憋屈～

**Comment by cvster** [comment]
不错
